name: Cron job for generating test results
on:
  schedule: 
    - cron: '42 12 * * *' # run the job once a day
  workflow_dispatch: # enable manual trigger for dev and test
jobs:
  remote_write:
    name: Generate compliance results for remote_write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.16.3'
      - name: "Check out repo and update results"
        run: |
          cd remote_write/
          ./generate-results.sh
          echo DONE
