name: Cron job for generating test results
on:
  schedule:
    - cron: '42 12 * * *' # run the job once a day
  workflow_dispatch: # enable manual trigger for dev and test
jobs:
  remote_write:
    name: Generate compliance results for remote_write
    runs-on: ubuntu-latest
    steps:
      - name: "Check out compliance harness"
        uses: actions/checkout@v2
      - name: "Set up Go environment"
        uses: actions/setup-go@v2
        with:
          go-version: 1.16.x
      - name: "Set environment variables"
        run: |
          echo "GO111MODULE=on" >> $GITHUB_ENV
      - uses: actions/cache@v2
        with:
          path: |
            ~/go/pkg/mod
            ~/.cache/go-build
            ~/Library/Caches/go-build
            %LocalAppData%\go-build
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: "Run tests"
        run: |
          cd ${GITHUB_WORKSPACE}/remote_write/
          ./generate-results.sh
          echo DONE
